server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    signerKey: "4j6Jauy+C/NJ06/FeTy5nRtW44VPv0ho2AZoICCQboZXYQnuD0UN5idYlrftsQJF"